### PR TITLE
[JENKINS-64139] Fix compatibility with core 2.264

### PR DESCRIPTION
**Pull request by res0nance**
Trying to get this to compile on the latest plugin-pom

### CODE REVIEW

**Review by timja — APPROVED** [review]
untested but looks good

**Comment by TonyNoble** [comment]
Hi @res0nance 

Thanks very much for the contribution - that's a significant amount of work you've had to put in.  Unfortunately, while it compiles, I get a javascript error (which prevents the job configuration page from loading) when attempting to use it:

```
Uncaught TypeError: ip is undefined
    <anonymous> http://localhost:8080/jenkins/adjuncts/d8a8e9f2/lib/form/repeatable/repeatable.js:159
    applySubtree http://localhost:8080/jenkins/static/d8a8e9f2/scripts/behavior.js:111
    applySubtree http://localhost:8080/jenkins/static/d8a8e9f2/scripts/behavior.js:107
    applySubtree http://localhost:8080/jenkins/static/d8a8e9f2/scripts/behavior.js:93
    apply http://localhost:8080/jenkins/static/d8a8e9f2/scripts/behavior.js:76
    start http://localhost:8080/jenkins/static/d8a8e9f2/scripts/behavior.js:71
    onload http://localhost:8080/jenkins/static/d8a8e9f2/scripts/behavior.js:125
    addLoadEvent http://localhost:8080/jenkins/static/d8a8e9f2/scripts/behavior.js:124
    createSearchBox http://localhost:8080/jenkins/static/d8a8e9f2/scripts/hudson-behavior.js:2400
    <anonymous> http://localhost:8080/jenkins/job/Test trigger job/configure:6
```

**Comment by res0nance** [comment]
@TonyNoble what version of jenkins are you using? Might be because i forgot the taglib marker file again. Could I trouble you to test it again? My current tests do not show any issues

**Comment by TonyNoble** [comment]
@res0nance 

This was when running via "mvn hpi:run", which uses the minimum Jenkins version specified in the pom (and any dependencies specified there).  Thanks for the update - will test again.

**Comment by TonyNoble** [comment]
@res0nance - That looks to have sorted it - cheers.  Will merge and get a release out.

Thanks again for your work!

**Pull request merged**
